keys:
- &admin_alex age1zdd3nu246uyx7zlfr07z52yssqp2dxp044ywsyn83nwgmudnnggq7yck7v
- &ru_server age1ue2w2zq09n2kxxawvr4mlsz7xvzqn54gvltt7jh0ft8vrculkgvs4ekxej
- &ee_server age1trmwmlh24mpj9l2sety2z9rdfepyc2xrz4wmlw95uujnjqhc643q3dj5jy
- &kz_server age1zww9096rdnefygzene2z605pdzakvstkfvjudwqq9l5hxfjdkp9skvpy28
creation_rules:
- path_regex: secrets/[^/]+\.(yaml|env|ini)$
  key_groups:
  - age:
    - *admin_alex
    - *ru_server
    - *ee_server
    - *kz_server
- path_regex: secrets/xray-server-config.json$
  key_groups:
  - age:
    - *admin_alex
    - *ru_server
    - *ee_server
    - *kz_server
- path_regex: secrets/.*ovpn$
  key_groups:
  - age:
    - *admin_alex
    - *ru_server
    - *ee_server
    - *kz_server
