# UFW Configuration
- name: Install UFW firewall
  apt: name=ufw update_cache=yes state=latest

- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow

- name: Set logging
  community.general.ufw:
    logging: 'on'

# - name: Allow all access to tcp port 7000
#   community.general.ufw:
#     rule: allow
#     port: '7000'
#     proto: tcp
#
# - name: Allow all access to udp ports 6000:6999
#   community.general.ufw:
#     rule: allow
#     port: '6000:6999'
#     proto: udp
