{
	"data": "ENC[AES256_GCM,data:hgd7NyMECyRPGacBNILXY9sdQiEWO5oxDj7RZhgmN8n0CQZWXBbge3G7/kX1zp6cVCa8xatukAbjJT1YF/xgJBcCMTGjpD2PgYi0h9VN+T4UpYJmlEWByvowokeBhkbyjXzX+VzQgabIr8/IPtg5QpjQpwfKmyGKdb1suZ0HHKHITlgxp7MJGRcg4k7zZwQ9X5Syd5IL6d9fQATphp2M8nQ3+wPqFbWeUZug9FXTpzbtaOW1o1ZZJ5pD9gV9OkA3O3Z1+cvlh3saQgVCM+K5Bngqo6m+mcvWzwkgD71ptyaYvDL9arsEIIu8Y6796LNY2DBPdotUGvRZxvHLfQ==,iv:kjPMqb8B8LDaXo/Tx76STSb7taOK7edmWwFScbceJpU=,tag:xPs5BdhGbfi18CxBIXjnDA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"azure_kv": null,
		"hc_vault": null,
		"age": [
			{
				"recipient": "age1zdd3nu246uyx7zlfr07z52yssqp2dxp044ywsyn83nwgmudnnggq7yck7v",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTGhUaXpwWmZESmNCY1d3\nNXpBbUQ2Y2ZOaEhGVTRTOVZVc2VUSFZkSzE4CkZKWVVCWEFEdnNEeENyYTlwaVJq\nZTg3RnUzS1ZlZUpLaUl4L0EwVUZJZE0KLS0tIEcrY1pkWi9EdTZIakJWUkdsN2I4\nTWJkM2J0TlZyNlNpa2paU0R2WStSSlkKpSPWkZ8qKCS/nI4M0EZ8UHOLAQXasBRR\nTZ/PnsbLc59fS5kWzd2DpCOdXz3zVaqZIfBLpP2JF0z7ijQlhqWk9A==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age142uruv9zjunvda0mmhaydmlc9d0xxfm39my7kk53u5evu5sudetsfe6zse",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4d1hFUDFQRHFtQzduTG1r\nR2hWalhjaTMwSlljYUNJL3JkQ2V4UUZ2WGxFCjFpVG12QUhCR3g1akNSSFhsaENj\nd2tsQ0YxVEYyYk5DejByVnpGcEZkbFUKLS0tIERvSWJEb05PaUpkRVNQK3lpU3pv\nVC9kamVqdXNsVGJ1ZjBWSUJib1huWU0Kf/ErhoPn1d04rYRer7R7+hsNdebJUe/e\nPQd+SrnQuMG4/CHkd2nRg7ennw2SnXzrWdXEEiNsOGTsbWtQQnOD+Q==\n-----END AGE ENCRYPTED FILE-----\n"
			},
			{
				"recipient": "age159r37qmngtr4878defjw5ey29lnzjmzkvq4jw6kszm3ghye9fesss4g83m",
				"enc": "-----BEGIN AGE ENCRYPTED FILE-----\nYWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3cWdubzRBU0VtRFpFK1BZ\nZFNTZnpZQVFrYTNHK2E1M0M2RWN1WG9iVkNVCkpoZkdaVEl4OWEyTGVjS01jU05D\nYjNyMjg2K1kwZXhkUFdvaWVGYjdhRkEKLS0tIHgyTG5zUFdlV0o4V2grTnpyYTl2\nMEx6TkFKQkIwL2MyNDdnSUVFaVJvOWsK/Mc0JPC8u1boOEsU+bVv+7yWhLg4a2Sk\nxN+x67+wxIxx3wbMqevPm7tggtlQFVT9XfECahZEHpbfiU6QBASF1w==\n-----END AGE ENCRYPTED FILE-----\n"
			}
		],
		"lastmodified": "2024-10-22T10:44:33Z",
		"mac": "ENC[AES256_GCM,data:tmhGq7/iCgSMkLN4U9C+y746gLK0Kvx3arLU55EqyLMd3LPtk6q7zWdPWoHK2d0Pw4D8zuc5QDsf63BzB4jSeFE8AREMWOwUvfX2+OPvUm0w2Oib+lSNR77Dm9Sw/ln0yt3OcdtVtYanpKFvmbhmhrPBUylheJ8U1qQ7lNPViCY=,iv:0vJ2FWcFrXJb0xAkpIuYT9y3TQUPSOuvt8xHah0zv9w=,tag:+p/4te946hMyiIKKGLjCUQ==,type:str]",
		"pgp": null,
		"unencrypted_suffix": "_unencrypted",
		"version": "3.9.0"
	}
}